# rules: dockerfile-source-not-pinned
# from: dockerfile/audit/dockerfile-source-not-pinned.yaml

. as $root
| ( ($root | scan_regex(["Dockerfile*"]; [
      "FROM\\s+(?P<IMAGE>\\S+)",
      "FROM\\s+(?P<IMAGE>\\S+):(?P<VERSION>\\S+)",
      "FROM\\s+(?P<IMAGE>\\S+):(?P<VERSION>\\S+)@(?P<HASH>\\S+)"
    ])) as $all
    | ( ($all | of(["FROM\\s+(?P<IMAGE>\\S+):(?P<VERSION>\\S+)@(?P<HASH>\\S+)"])
          | where_capture_not("HASH"; "^(?:sha256:)"))
          + ($all | of(["FROM\\s+(?P<IMAGE>\\S+)"])
          | at_same_place(($all | of(["FROM\\s+(?P<IMAGE>\\S+):(?P<VERSION>\\S+)"])))
          | outside($all | of(["FROM\\s+(?P<IMAGE>\\S+):(?P<VERSION>\\S+)@(?P<HASH>\\S+)"])))
        | finding("dockerfile-source-not-pinned";
            "To ensure reproducible builds, pin Dockerfile `FROM` commands to a specific hash.") ) )
| report
