package string

import "github.com/itchyny/gojq"

// RegisterAll registers every string cmdlet, the existing four and the case,
// text, predicate and pattern utilities.
func RegisterAll() []gojq.CompilerOption {
	return []gojq.CompilerOption{
		RegisterReplace(),
		RegisterSlugify(),
		RegisterSnakeCase(),
		RegisterKebabCase(),
		RegisterCamelCase(),
		RegisterPascalCase(),
		RegisterTitleCase(),
		RegisterTruncate(),
		RegisterPadLeft(),
		RegisterPadRight(),
		RegisterMask(),
		RegisterCountOccurrences(),
		RegisterIsBlank(),
		RegisterIsAlphanumeric(),
		RegisterIsAlphabetic(),
		RegisterIsNumericString(),
		RegisterIsUppercase(),
		RegisterIsLowercase(),
		RegisterIsAscii(),
		RegisterWordCount(),
		RegisterNormalizeWhitespace(),
		RegisterAcronym(),
		RegisterEscapeRegex(),
		RegisterIsRegexValid(),
		RegisterGlobToRegex(),
		RegisterMatchGlob(),
		RegisterStripANSI(),
		RegisterTemplate(),
		RegisterWrapText(),
		RegisterIndent(),
		// Regex
		// Text tools
		RegisterReverseWords(),
		RegisterTruncateWords(),
		RegisterRemoveAccents(),
		RegisterSentenceCase(),
		RegisterLineCount(),
		RegisterDedent(),
		RegisterSwapCase(),
		RegisterCharFrequencies(),
		RegisterReverseLines(),
		RegisterUniqueLines(),
		RegisterSortLines(),
		RegisterStripQuotes(),
		RegisterPadCenter(),
		// Text extras
		RegisterBeforeFirst(),
		RegisterAfterFirst(),
		RegisterSurround(),
		RegisterSoundex(),
		RegisterCountVowels(),
		RegisterCountConsonants(),
		RegisterCapitalizeFirst(),
		RegisterUnicodeEscape(),
		RegisterUnicodeUnescape(),
		RegisterDiffLines(),
		// Text extras, part three
		RegisterQuotedPrintableEncode(),
		RegisterQuotedPrintableDecode(),
		RegisterPrefixLines(),
		RegisterFirstLines(),
		RegisterLastLines(),
		RegisterIsBalanced(),
	}
}
